<template>
  <LoadingOverlay :active="isLoading">
    <div class="loadingio-spinner-cube-6jyzrm4m0ef">
      <div class="ldio-33mawtsdtv7">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </LoadingOverlay>
</template>

<script>
import { mapState } from 'pinia';
import loadingStore from '@/stores/loadingStore';

export default {
  computed: {
    ...mapState(loadingStore, ['isLoading']),
  },
};
</script>

<style scoped>
@keyframes ldio-33mawtsdtv7 {
  0% {
    transform: scale(1.1500000000000001);
  }
  100% {
    transform: scale(1);
  }
}
.ldio-33mawtsdtv7 div {
  position: absolute;
  width: 40px;
  height: 40px;
  top: 6.666666666666668px;
  left: 6.666666666666668px;
  background: #361707;
  animation: ldio-33mawtsdtv7 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.3s;
}
.ldio-33mawtsdtv7 div:nth-child(2) {
  top: 6.666666666666668px;
  left: 53.33333333333333px;
  background: #5c270d;
  animation-delay: -0.2s;
}
.ldio-33mawtsdtv7 div:nth-child(3) {
  top: 53.33333333333333px;
  left: 6.666666666666668px;
  background: #fff1cd;
  animation-delay: 0s;
}
.ldio-33mawtsdtv7 div:nth-child(4) {
  top: 53.33333333333333px;
  left: 53.33333333333333px;
  background: #914e1a;
  animation-delay: -0.1s;
}
.loadingio-spinner-cube-6jyzrm4m0ef {
  width: 100px;
  height: 100px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-33mawtsdtv7 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-33mawtsdtv7 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
